package:
  name: placekey
  version: "0.0.10"
source:
  fn: placekey-0.0.10.tar.gz
  url: https://files.pythonhosted.org/packages/8b/09/1dee6f74eff17de746fde8e16141fffe839448f57c7d3c8925f2f30f547f/placekey-0.0.10.tar.gz
  md5: "c92e790d5f32ced496120663412a1f83"
###build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  ###noarch: python
  ###number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # skip: True  # [py<36]
  ###script: "{{ PYTHON }} -m pip install . -vv"
build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        PLACEKEY_API_KEY: ${{ secrets.PLACEKEY_API_KEY }}
      run: |
        pytest placekey/tests/test_placekey.py
        pytest -m"not slow" placekey/tests/test_api.py
requirements:
  build:
    - pip
    - python
  run:
    - python
#adding test links
test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - unittest
    - h3.api.basic_int
    - shapely
    - placekey
about:
  home: https://github.com/Placekey/placekey-py
  license: Apache-2.0 
  license_file: LICENSE.txt
  summary: A Python library for working with Placekeys. Documentation for this package can be found here, and documentation for the Placekey service API can be found here. The Plackey design specification is available here. The details in Placekey encoding is here. We welcome your feedback.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - Trippl7777
