package:
  name: placekey
  version: "0.0.10"
about:
  home: https://github.com/Placekey/placekey-py
  license: Apache
  summary: A Python library for working with Placekeys. Documentation for this package can be found here, and documentation for the Placekey service API can be found here. The Plackey design specification is available here. The details in Placekey encoding is here. We welcome your feedback.
source:
  fn: placekey-0.0.10.tar.gz
  url: https://files.pythonhosted.org/packages/8b/09/1dee6f74eff17de746fde8e16141fffe839448f57c7d3c8925f2f30f547f/placekey-0.0.10.tar.gz
  md5: "c92e790d5f32ced496120663412a1f83"

requirements:
  build:
    - pip >=19
    - python >=3.6
  run:
    - python >=3.6