{% set name = "placekey" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/8b/09/1dee6f74eff17de746fde8e16141fffe839448f57c7d3c8925f2f30f547f/placekey-0.0.10.tar.gz
  sha256: 25235e7d5733ba229464fa4de0dacfeda84063b9fbb52041ac67d04c9c35d6be

build:
  number: 0
  noarch: python
  # script: {{ PYTHON }} -m pip install . -vv
  script: python setup.py install



  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: ['3.6', '3.7', '3.8']

  steps:
  - uses: actions/checkout@v2
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      python -m pip install flake8 pytest
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - name: Lint with flake8
    run: |
      # stop the build if there are Python syntax errors or undefined names
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - name: Test with pytest
    env:
      PLACEKEY_API_KEY: ${{ secrets.PLACEKEY_API_KEY }}
    run: |
      pytest placekey/tests/test_placekey.py
      pytest -m"not slow" placekey/tests/test_api.py

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - setuptools-scm
    - regex
    - h3
    - shapely

test:
  imports:
    - placekey
    - placekey.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.placekey.io/how-it-works
  summary: Placekey is a free, universal standard identifier for any physical place, so that the data pertaining to those places can be shared across datasets and organizations easily.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Trippl7777
#add line to appease lint gods
